### PR TITLE
Don't throw on walking empty ranges

### PR DESCRIPTION
**Pull request by tonistiigi**

### CODE REVIEW

**Comment by dcodeIO** [comment]
I haven't yet looked over this in detail, but `!ptr.parent.nodes` shouldn't be a valid test as `nodes` either is an array or not present (`parent` is null). Or am I missing something here?

**Comment by tonistiigi** [comment]
Yes, I wasn't sure either where to put the check on `walkDesc()` so feel free to change it to something more readable.  In my test case `ptr.parent` only has a root property and so the next line throws when `asearch()` is called with `undefined`. Its the last testcase that should walk from 0 to 1.

**Comment by dcodeIO** [comment]
Ok, thank you, I've (hopefully) fixed this and merged your test case.

**Comment by tonistiigi** [comment]
Thanks!

**Pull request closed without merging**
